# Generated by Django 5.1.4 on 2024-12-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testes',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.TextField(max_length=255)),
            ],
        ),
    ]
