# Generated by Django 5.1.4 on 2024-12-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testes',
            name='login',
            field=models.CharField(max_length=255),
        ),
    ]
