# Generated by Django 5.1.4 on 2025-01-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_testes_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produto', models.IntegerField()),
                ('des_produto', models.TextField(max_length=255)),
                ('qtd_produtos', models.IntegerField()),
                ('validade_produto', models.DateField()),
                ('setor', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='testes',
        ),
    ]
